# Generated by Django 4.2.23 on 2025-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
