# Generated by Django 4.2.23 on 2025-06-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_monthlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('drywall', 'Drywall'), ('aluminum', 'Aluminum')], max_length=20)),
                ('blueprints', models.FileField(blank=True, null=True, upload_to='blueprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(limit_choices_to={'user_type': 'worker'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
