# Generated by Django 4.2.23 on 2025-06-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_remove_customuser_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default=12345, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='contractor',
            field=models.OneToOneField(default=12345, limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'worker'}, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
