# Generated by Django 4.2.23 on 2025-06-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_company_created_at_company_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.CharField(max_length=50, unique=True)),
                ('door_type', models.CharField(choices=[('sliding', 'Sliding Door'), ('multi_bolt', 'Multi-Bolt Door')], max_length=10)),
                ('number_of_sashs', models.IntegerField()),
                ('aluminum_type', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7)),
                ('glass_type', models.CharField(choices=[('transparent', 'Transparent'), ('anti_sun', 'Anti-Sun'), ('shadowed', 'Shadowed'), ('בודדי', 'בודדי')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.CharField(max_length=50, unique=True)),
                ('window_type', models.CharField(choices=[('sliding', 'Sliding'), ('multi_bolt', 'Multi-Bolt')], max_length=10)),
                ('number_of_sashs', models.IntegerField()),
                ('aluminum_type', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='WindowSash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.DecimalField(decimal_places=2, max_digits=7)),
                ('top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_sashes', to='accounts.glass')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_sashes', to='accounts.window')),
            ],
        ),
        migrations.CreateModel(
            name='WindowFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.DecimalField(decimal_places=2, max_digits=7)),
                ('top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('window', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='window_frame', to='accounts.window')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('material_thickness', models.CharField(choices=[('37', '37mm'), ('50', '50mm'), ('70', '70mm'), ('100', '100mm'), ('F47', 'F47')], max_length=3)),
                ('drywall_type', models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('pink', 'Pink'), ('blue', 'Blue')], max_length=5)),
                ('stud_type', models.CharField(choices=[('metal', 'Metal')], max_length=5)),
                ('track_type', models.CharField(choices=[('metal', 'Metal')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='DoorSash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.DecimalField(decimal_places=2, max_digits=7)),
                ('top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=7)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_sashes', to='accounts.door')),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_sashes', to='accounts.glass')),
            ],
        ),
        migrations.CreateModel(
            name='DoorFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.DecimalField(decimal_places=2, max_digits=7)),
                ('top', models.DecimalField(decimal_places=2, max_digits=7)),
                ('door', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='door_frame', to='accounts.door')),
            ],
        ),
    ]
