# Generated by Django 4.2.23 on 2025-06-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_door_glass_window_windowsash_windowframe_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_type', models.CharField(choices=[('transparent', 'Transparent'), ('anti_sun', 'Anti-Sun'), ('shadowed', 'Shadowed'), ('בודדי', 'בודדי')], max_length=20)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'glass_type')},
            },
        ),
        migrations.CreateModel(
            name='DrywallPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drywall_type', models.CharField(max_length=10)),
                ('material_thickness', models.CharField(max_length=5)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'drywall_type', 'material_thickness')},
            },
        ),
        migrations.CreateModel(
            name='AluminumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluminum_type', models.CharField(max_length=10)),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'aluminum_type')},
            },
        ),
    ]
