# Generated by Django 4.2.23 on 2025-07-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_glassprice_drywallprice_aluminumprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_type',
            field=models.CharField(choices=[('sliding', 'Sliding'), ('multi_bolt', 'Multi-Bolt')], max_length=10),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blueprint', models.FileField(blank=True, null=True, upload_to='room_blueprints/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.project')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors', to='accounts.room'),
        ),
        migrations.AddField(
            model_name='window',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows', to='accounts.room'),
        ),
    ]
