# Generated by Django 4.2.23 on 2025-07-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_door_door_type_room_door_room_window_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
