# Generated by Django 4.2.23 on 2025-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_glass_price_delete_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorframe',
            name='bottom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
