# Generated by Django 4.2.23 on 2025-08-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_doorframe_bottom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('drywall_type', models.CharField(choices=[('white', 'White'), ('pink', 'Pink (Fire-Resistant)'), ('green', 'Green (Moisture-Resistant)'), ('blue', 'Blue (Acoustic)')], max_length=10)),
                ('stud_thickness', models.CharField(choices=[('37', '37mm'), ('50', '50mm'), ('70', '70mm'), ('100', '100mm'), ('f47', 'F47')], max_length=10)),
                ('number_of_layers', models.PositiveSmallIntegerField(default=1)),
                ('double_sided', models.BooleanField(default=False)),
                ('board_length', models.DecimalField(choices=[(2.0, '2000 mm (2.0 m)'), (2.6, '2600 mm (2.6 m)'), (3.0, '3000 mm (3.0 m)')], decimal_places=1, default=2.6, max_digits=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='accounts.room')),
            ],
        ),
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('drywall_type', models.CharField(choices=[('white', 'White'), ('pink', 'Pink (Fire-Resistant)'), ('green', 'Green (Moisture-Resistant)'), ('blue', 'Blue (Acoustic)')], max_length=10)),
                ('stud_thickness', models.CharField(choices=[('37', '37mm'), ('50', '50mm'), ('70', '70mm'), ('100', '100mm'), ('f47', 'F47')], max_length=10)),
                ('board_length', models.DecimalField(choices=[(2.0, '2000 mm (2.0 m)'), (2.6, '2600 mm (2.6 m)'), (3.0, '3000 mm (3.0 m)')], decimal_places=1, default=2.6, max_digits=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceilings', to='accounts.room')),
            ],
        ),
    ]
