# Generated by Django 4.2.23 on 2025-08-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wall_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DrywallMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_board_count', models.PositiveIntegerField(default=0)),
                ('total_stud_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_track_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drywall_material', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='AluminumMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_top_bottom_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('frame_side_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sash_side_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sash_top_bottom_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sash_handle_side_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluminum_material', to='accounts.project')),
            ],
        ),
    ]
