# Generated by Django 4.2.23 on 2025-08-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_hourly_wage_drywallmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrywallBoardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('price_per_board', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='MetalProfilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(max_length=10)),
                ('thickness', models.CharField(max_length=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'profile_type', 'thickness')},
            },
        ),
        migrations.DeleteModel(
            name='DrywallPrice',
        ),
    ]
