# Generated by Django 4.2.23 on 2025-08-08 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_drywallboardprice_metalprofileprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1700', '1700'), ('7000', '7000'), ('7300', '7300'), ('9000', '9000'), ('9200', '9200'), ('2200', '2200'), ('9400', '9400'), ('2000', '2000'), ('4500', '4500'), ('4400', '4400'), ('4300', '4300')], max_length=10)),
                ('use', models.CharField(choices=[('window', 'Window'), ('door', 'Door')], max_length=10)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='TEMP', max_length=20, unique=True)),
                ('material_type', models.CharField(choices=[('drywall', 'Drywall'), ('aluminum', 'Aluminum'), ('glass', 'Glass')], max_length=20)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('contractor', models.ForeignKey(limit_choices_to={'user_type': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screw_type', models.CharField(choices=[('drywall', 'Drywall'), ('dowel', 'Dowel'), ('screw', 'Regular Screw'), ('stainless', 'Stainless Steel')], max_length=20)),
                ('length_cm', models.DecimalField(choices=[(2.5, '2.5 cm'), (3.5, '3.5 cm'), (4.5, '4.5 cm'), (5.0, '5 cm'), (7.0, '7 cm'), (10.0, '10 cm')], decimal_places=1, max_digits=4)),
                ('count_per_box', models.PositiveIntegerField(choices=[(100, '100'), (500, '500'), (1000, '1000'), (10000, '10000')])),
                ('price_per_100', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('code_string', models.CharField(max_length=50)),
                ('set_code', models.PositiveIntegerField(unique=True)),
                ('weight_per_meter', models.DecimalField(decimal_places=3, max_digits=6)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('aluminum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='accounts.aluminumprofile')),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='MetalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('stud', 'Stud'), ('track', 'Track')], max_length=10)),
                ('size', models.CharField(choices=[('37', '37 mm'), ('50', '50 mm'), ('70', '70 mm'), ('100', '100 mm'), ('f47', 'F47')], max_length=10)),
                ('length_meters', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrywallBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('pink', 'Pink'), ('green', 'Green'), ('white', 'White'), ('blue', 'Blue')], max_length=20)),
                ('size', models.CharField(choices=[('200x120', '200 x 120 cm'), ('260x120', '260 x 120 cm'), ('300x120', '300 x 120 cm')], max_length=20)),
                ('thickness_mm', models.PositiveIntegerField(default=12)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_board', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
