# Generated by Django 5.2.6 on 2025-09-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceiling',
            name='height',
        ),
        migrations.RemoveField(
            model_name='ceiling',
            name='width',
        ),
        migrations.AddField(
            model_name='ceiling',
            name='area',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=8),
            preserve_default=False,
        ),
    ]
